### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'XXX/.venv/lib/python3.5/site-packages/CHANGES.rst'

### ISSUE THREAD

**Issue by rg3915** [rhenter/django-stuff#2]
Erro após instalar e rodar o django com django-stuff.
Eu coloquei o `django_stuff` em INSTALLED_APPS, mas
```
$ python manage.py 
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/tmp/dj/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/tmp/dj/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/tmp/dj/.venv/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/tmp/dj/.venv/lib/python3.5/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/tmp/dj/.venv/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/dj/.venv/lib/python3.5/site-packages/django_stuff/__init__.py", line 4, in <module>
    from .version import version  # noqa
  File "/tmp/dj/.venv/lib/python3.5/site-packages/django_stuff/version.py", line 24, in <module>
    version = get_version()
  File "/tmp/dj/.venv/lib/python3.5/site-packages/django_stuff/version.py", line 15, in get_version
    with codecs.open(changes, encoding='utf-8') as changes:
  File "/usr/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/dj/.venv/lib/python3.5/site-packages/CHANGES.rst'
```

**Comment by rhenter** [comment]
Arrumei e esqueci de commitar.

**Comment by rhenter** [comment]
Corrigi e gerei uma versão nova `0.1.11`
